#!/bin/bash

# =================================================================================
# create_persistent_disk_rules.sh
#
# This script creates a udev rule file to ensure persistent disk names across
# reboots for an OpenShift Bare Metal cluster with HPE RAID.
#
# It identifies disks by their size, finds their unique hardware ID, and
# generates a udev rule to create a stable symbolic link in /dev/.
#
# =================================================================================

set -e # Exit immediately if a command exits with a non-zero status.
set -o pipefail # The return value of a pipeline is the status of the last command to exit with a non-zero status.

# --- Configuration ---
# Define the mapping of the desired persistent name to the disk's size.
# IMPORTANT: Adjust the size value (e.g., "1T", "7T") to match what 'lsblk'
# reports on your system. Use 'lsblk -dno NAME,SIZE' to verify.
declare -A DISK_MAP
DISK_MAP=(
    ["osdisk"]="1T"
    ["data-dev"]="7T"
    ["data-dr"]="11T"
)

# The udev rule file to be created.
UDEV_RULES_FILE="/etc/udev/rules.d/99-persistent-disks.rules"

# --- Script Logic ---

# 1. Check for root privileges
if [[ "${EUID}" -ne 0 ]]; then
  echo "This script must be run as root. Please use 'sudo'."
  exit 1
fi

echo "--- Starting Persistent Disk Naming Script ---"

# 2. Prepare the rules content
UDEV_RULES_CONTENT="# This file was automatically generated by a script to create persistent disk names\n"
UDEV_RULES_CONTENT+="# Do not edit this file manually without understanding the consequences.\n\n"

# 3. Iterate over the disk map to find each disk and generate its rule
for NAME in "${!DISK_MAP[@]}"; do
    SIZE="${DISK_MAP[$NAME]}"
    echo "Processing disk: ${NAME} (expected size: ${SIZE})"

    # Find the device name (e.g., sda, sdb) by its size.
    # We search for a line that starts with the size, which is safer.
    DEVICE_NAME=$(lsblk -dno SIZE,NAME | grep "^${SIZE}" | awk '{print $2}')

    if [[ -z "${DEVICE_NAME}" ]]; then
        echo "ERROR: Could not find a disk with size '${SIZE}'."
        echo "Please verify the size in the script matches the output of 'lsblk -dno SIZE,NAME'."
        exit 1
    fi

    echo "  > Found device '${DEVICE_NAME}' for size '${SIZE}'."

    # Get the unique ID_SERIAL for the discovered device. For HPE RAID, this is the most reliable identifier.
    DISK_SERIAL=$(udevadm info -q property -n "/dev/${DEVICE_NAME}" | grep 'ID_SERIAL=' | cut -d'=' -f2)

    if [[ -z "${DISK_SERIAL}" ]]; then
        echo "ERROR: Could not retrieve ID_SERIAL for '/dev/${DEVICE_NAME}'."
        echo "This identifier is crucial for creating a persistent rule."
        exit 1
    fi

    echo "  > Found unique ID_SERIAL: '${DISK_SERIAL}'."

    # Construct the udev rule for this disk
    RULE="KERNEL==\"sd*\", ENV{ID_SERIAL}==\"${DISK_SERIAL}\", SYMLINK+=\"${NAME}\""
    UDEV_RULES_CONTENT+="${RULE}\n"
    echo "  > Generated Rule: ${RULE}"
done

# 4. Write the generated rules to the udev file
echo -e "\n--- Applying udev rules ---"
echo "The following rules will be written to ${UDEV_RULES_FILE}:"
echo "----------------------------------------------------"
echo -e "${UDEV_RULES_CONTENT}"
echo "----------------------------------------------------"

# Use a heredoc to safely write the content to the file
cat > "${UDEV_RULES_FILE}" <<-EOF
${UDEV_RULES_CONTENT}
EOF

echo "  > Successfully wrote rules to ${UDEV_RULES_FILE}."

# 5. Reload udev rules and trigger the new rules to apply them
echo "Reloading udev rules and triggering..."
udevadm control --reload-rules
udevadm trigger
echo "  > udev rules reloaded and triggered."

# 6. Final verification
echo -e "\n--- Script Finished Successfully ---"
echo "Persistent disk names should now be created."
echo "Please verify by running the following command:"
echo "ls -l /dev/osdisk /dev/data-dev /dev/data-dr"
echo "The output should show symbolic links to the correct /dev/sdX devices."

exit 0
